### ISSUE TITLE
Ability to override built-in components

### ISSUE THREAD

**Issue by txemaleon** [9gustin/react-notion-render#109]
Hi!

I'm using `react-notion-render` in one of my projects with `Next.js`.

I'd like to take advantage of their [built-in image optimization](https://nextjs.org/docs/basic-features/image-optimization) and their [`Link` optimization](https://nextjs.org/docs/api-reference/next/link), which requires to override default `img` and `a` tags this package provides.

I'd like to override the link component and `img` component your package offers but there is no way since the code only uses built-in components.

**Comment by 9gustin** [comment]
Hey! thanks for the suggestion, i have the idea to include this as a render prop, to add custom render to any block, when i have released i notice you for here 😸

**Comment by losfair** [comment]
In my project I'm currently using a hack (https://github.com/losfair/react-notion-render/commit/de4f699dc12a6e309a8205ca689c00b21846eb53) to add my own custom components. It would be nice to have support for `Render`-scoped, user-provided custom components :)

**Comment by 9gustin** [comment]
Haha, nice idea! custom-custom components 🤔 

Yeah i understand that's an important feature. By now i not start working on it, just have ideas, Im going to try start it in this weekend 😄

**Comment by 9gustin** [comment]
Solved in latest version 😄 

Install with 
``npm i @9gustin/react-notion-render@3.9.0`

Here the npm link of version:
https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.9.0

**Comment by codercatdev** [comment]
@9gustin thank you for this, couldn't be running codingcat.dev without it!!

**Comment by 9gustin** [comment]
I'm so happy for it! anything that you need or any idea for package are welcome <3

**Comment by txemaleon** [comment]
Hey, I want to thank you too!
