### ISSUE TITLE
Images are not rendering without caption

### ISSUE THREAD

**Issue by nublson** [9gustin/react-notion-render#114]
Since I installed the new latest version, the images are not rendering without a caption and the images with caption are being rendered without the caption.

I needed to downgrade the library

**Comment by 9gustin** [comment]
Hey, sorry about it. Im going to review it in these days! 🙂

**Comment by 9gustin** [comment]
@nublson  Solved, thanks for waiting I had a busy few days. Install latest rnr version with `npm i @9gustin/react-notion-render@latest`

**Comment by rajeshg** [comment]
Wow. Thanks for fixing this @9gustin

**Comment by nublson** [comment]
@9gustin sorry for not responding, I didn't see your message.
The images are being rendered but the caption doesn't, they just appear as alt property on the image.
