### ISSUE TITLE
Custom component breaks code blocks

### ISSUE THREAD

**Issue by losfair** [9gustin/react-notion-render#116]
The code block:

```scala
sealed abstract class Option[T]

case class Some[T](x: T) extends Option[T]
case object None extends Option[Nothing]
```

is rendered to:

```html
<pre><code class="undefined language-scala"><a href="x: T" class="" target="_blank" rel="noreferrer">T</a></code></pre>
```

Looks like that the `Link` custom component:

https://github.com/9gustin/react-notion-render/blob/0a56d7250efdb1e7e9bd4db81adaa95ea5c394ec/src/hoc/withCustomComponent/constants.ts#L46-L55

matched and replaced the text inside the code block.

My code is:

```tsx
<Render blocks={blocks} simpleTitles />
```

**Comment by 9gustin** [comment]
True! i would working on it in these days

**Comment by 9gustin** [comment]
Released as beta, if you want to test it you can install with `npm i @9gustin/react-notion-render@beta` (https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.8.2-beta.0)

In these days im going to test it and release v3.8.2 ✨

**Comment by losfair** [comment]
Thanks for the fix! It seems that there're still some issues with inline code:

```
inline: `case class Some[T](x: T) extends Option[T]`
```

renders to:

```
<p>inline: <a href="x: T" class="rnr-code" target="_blank" rel="noreferrer">T</a></p>
```

**Comment by 9gustin** [comment]
you have tested it with beta version? yet not was be deployed as normal version, just available in beta to test it. In my case i've created a page with this code and it was be rendered correctly: 

Here be the example: https://blog-template.9gustin.com/84dcf55a-fabe-4fd2-9ca6-418d48437baf

You can test it with `npm i @9gustin/react-notion-render@beta`

**Comment by 9gustin** [comment]
understand, going to review it 🤔

**Comment by 9gustin** [comment]
Fixed, by now i only solved the issue rendering the code as: 

`<code class="rnr-inline-code">some inline code</code>`

Maybe it would be improved thinking on giving styles, but for now the important part is that renders correctly. Published as beta: 
[v3.8.2-beta.1](https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.8.2-beta.1)

@losfair

**Comment by losfair** [comment]
Upgrading to `3.8.2-beta.1` fixed the issue for me. Thanks!
