### ISSUE TITLE
Rich Text Support

### ISSUE THREAD

**Issue by pgerlich** [9gustin/react-notion-render#132]
It looks like the API might have changed recently. Now they use `rich_text` instead of just `text`? All of my blocks are coming back empty because the rich_text field isn't parsed. I might open a PR to fix this.

**Comment by 9gustin** [comment]
Oh! thanks for notice that, if you can make it i really apreciate. If not im going to work on this more later/tomorrow ❤️ 

@pgerlich

**Comment by 9gustin** [comment]
rdy, you can install v3.8.3(latest) with these changes.

https://www.npmjs.com/package/@9gustin/react-notion-render

`npm i @9gustin/react-notion-render@latest`
