### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by codercatdev** [9gustin/react-notion-render#144]
While using Next.js I am receiving this error after switching to this package. 
It is really difficult to track down what is causing the issue.

If you go to https://codingcat-6p4h0qclb-codercatdev.vercel.app/tutorial/integrating-storybook-with-sveltekit
then click any of the Tutorial links under "Latest Tutorials". You will see a client side error occur. If I then refresh the page it will work correctly.

Here is me walking through it.
https://www.loom.com/share/7ab0fcd2a14f4e8b8349fbd11182360f

<img width="982" alt="image" src="https://user-images.githubusercontent.com/3102249/173348311-8fdb396a-e3d1-43cb-9ba7-99fa62da0953.png">

**Comment by 9gustin** [comment]
Can give me the page in Notion or the JSON of blocks that are causing this?

**Comment by codercatdev** [comment]
@9gustin would there be a way to replace the Code function that you have using custom components?
I would really rather use the package `prism-react-renderer`.

```
import Highlight, { defaultProps, Language } from 'prism-react-renderer';
import dracula from 'prism-react-renderer/themes/vsDark';
import { useState } from 'react';
import WordHighlight from './WordHighlight';

const CodeHighlight = ({
  children,
  className,
  lang,
  highlight,
}: {
  children: string;
  className: string;
  lang?: string;
  highlight?: string[];
}) => {
  const language =
    lang || className?.replace(/language-/, '') || ('bash' as any);

  const getTokenSetup = ({ getTokenProps, token, key }: any) => {
    const tokenProps = getTokenProps({ token, key });
    if (highlight && highlight.includes(token.content)) {
      return <WordHighlight>{token.content}</WordHighlight>;
    }
    return <span key={key} {...tokenProps} />;
  };

  const Button = (props: any) => (
    <button
      style={{
        position: 'absolute',
        top: 0,
        right: 0,
        border: 'none',
        boxShadow: 'none',
        textDecoration: 'none',
        margin: '8px',
        padding: '8px 12px',
        background: '#E2E8F022',
        color: 'white',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '14px',
        fontFamily: 'sans-serif',
        lineHeight: '1',
      }}
      {...props}
    />
  );

  const [isCopied, setIsCopied] = useState(false);
  const copyToClipboard = (str:string) => {
    const el = document.createElement('textarea');
    el.value = str;
    el.setAttribute('readonly', '');
    el.style.position = 'absolute';
    el.style.left = '-9999px';
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
  };

  return (
    <Highlight
      {...defaultProps}
      code={children}
      language={language}
      theme={dracula}
    >
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <pre
          className={className}
          style={{ ...style, padding: '2rem', position: 'relative' }}
        >
          <Button
            onClick={() => {
              copyToClipboard(children);
              setIsCopied(true);
              setTimeout(() => setIsCopied(false), 3000);
            }}
          >
            {isCopied ? '🎉 Copied!' : 'Copy'}
          </Button>
          {tokens.map((line, i) => (
            <div key={i} {...getLineProps({ line, key: i })}>
              {line.map((token, key) =>
                getTokenSetup({ getTokenProps, token, key })
              )}
            </div>
          ))}
        </pre>
      )}
    </Highlight>
  );
};
export default CodeHighlight;
```

**Comment by 9gustin** [comment]
You can use just prism like that if im not wrong: https://github.com/9gustin/react-notion-render/wiki/About-code-blocks-and-how-to-colorize-it-%F0%9F%8E%A8 I dont know the difference with `prism-react-renderer`

To use a custom block for code im thinking in a prop to receive a custom component to a block type. I have something developed but not tested, i can take it and release it as beta today, this can works (but i need some hours to publish).

Here have an example about: https://github.com/9gustin/react-notion-render/blob/feature/customBlockMapper/dev-example/pages/%5Bid%5D.js#L15 , the idea its you can pass an component for a type.

**Comment by codercatdev** [comment]
I agree the prism example you have works great until I try to add

`prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard`

In next.js when you change routes I get the above error. 

It would be totally sweet to swap components though by passing in your own. This is how I was handling it with Sanity.io blocks.

**Comment by 9gustin** [comment]
understanded! today i work on this and release a beta version with prop to receive custom components to render it. I notify you when it's done.
