### ISSUE TITLE
Unable to Resolve Dependency Tree Error

### ISSUE THREAD

**Issue by bytrangle** [9gustin/react-notion-render#161]
I'm using the latest Next.js template, so that means it uses React ^18.0. I got the Dependency Tree error when installing this package, because it uses React ^17.0.

I worked around that by adding the flag `legacy-peer-deps`, but what's your recommended solution?

**Comment by 9gustin** [comment]
Im going to update the version of peerDependencies

**Comment by 9gustin** [comment]
@bytrangle hey! i have released `3.10.0-beta.1`, this update all package libraries, including react peerDependency. If you want you can test it by now in beta and im going to release as final in these days.

install it with 
`yarn add @9gustin/react-notion-render@beta`

And tell me if you see something wrong 💖
