### ISSUE TITLE
Add prop to view images on modal onClick

### ISSUE THREAD

**Issue by 9gustin** [9gustin/react-notion-render#49]
Add a modal to view images when use clicks on them.

This must be a prop. Not force that to all images.

**Comment by mrzmyr** [comment]
Isn't this out of scope of a renderer? As far as I know, the notion app only shows the image itself without a modal functionality. Am I missing something here?

**Comment by 9gustin** [comment]
yes, it's true, but i think it as an extra-functionality for the package. For this i say that would be optional. Maybe can be a nice feature for some cases

**Comment by mrzmyr** [comment]
I definitely agree that it's a great feature to have, but I would insist not to add it to the renderer itself. Maybe it's a good idea to have another repo which acts as a plugin to this renderer. What do you think about that?

**Comment by 9gustin** [comment]
mmmmm interesting, I think all of these things as a prop of Render, but it's a good idea to think it as a plugin. i Like it.
