### ISSUE TITLE
Add Video Custom component

### ISSUE THREAD

**Issue by 9gustin** [9gustin/react-notion-render#50]
I want to show videos in my page. Add that as a [custom component](https://github.com/9gustin/react-notion-render/issues/49) and take the format from markdown

**Comment by 9gustin** [comment]
contemplate YouTube embeds

**Comment by AnibalDBXD** [comment]
#52 Pull requests

**Comment by 9gustin** [comment]
Solved! nice @AnibalDBXD 😄
