### ISSUE TITLE
Apply the new changes of the API of Notion

### ISSUE THREAD

**Issue by w-agustin-vazquez** [9gustin/react-notion-render#53]
Link: https://twitter.com/NotionAPI/status/1431311141800583169?s=20

**Comment by 9gustin** [comment]
v3.3 beta it's available with notion native videos 😄 -> https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.3.0-beta.0

**Comment by 9gustin** [comment]
File component are available in https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.3.0-beta.1 🚀

**Comment by 9gustin** [comment]
About bookmarks, it's not possible. to fetch url(title, image, description) data it's needed a backend to avoid CORS problems

**Comment by 9gustin** [comment]
Embeds and PDF are in https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.3.0-beta.2 🚀

**Comment by 9gustin** [comment]
All ready! https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.3.0-beta.3 🚀 
Today this version would be available 😄

**Comment by 9gustin** [comment]
Released v3.3.0 🚀 -> https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.3.0
