### ISSUE TITLE
New Block types added 

### ISSUE THREAD

**Issue by onlineworld69** [9gustin/react-notion-render#60]
Dear friend. Tks for developing such a great tool. 

I just want to let u know there are more block types supported by notion. Check it out and would love to see your render support these. Tks again!

https://developers.notion.com/changelog/callouts-and-quote-blocks-are-now-supported

**Comment by 9gustin** [comment]
great! i will work on it these days, thanks 😃

**Comment by 9gustin** [comment]
Tomorrow I will do some tests and deploy this version 💪🏼

**Comment by onlineworld69** [comment]
Trying the new version out and it’s working ;) I just needa follow your instruction for styling to make my website nicer ;) Thank you for your great work!

**Comment by 9gustin** [comment]
Released!
