### ISSUE TITLE
I found a bug that broke the render

### ISSUE THREAD

**Issue by onlineworld69** [9gustin/react-notion-render#63]
Please advise! 

<img width="1103" alt="Screen Shot 2021-10-14 at 22 07 25" src="https://user-images.githubusercontent.com/13715145/137345567-8d966b2b-543b-4226-aa27-1d353db927e9.png">

`The Notion Response:`

;[
  {
    object: 'block',
    id: '8b52415c-bb4f-4a2c-bbea-290ed92be526',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'paragraph',
    paragraph: {
      text: [
        {
          type: 'text',
          text: { content: '          ', link: null },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'default',
          },
          plain_text: '          ',
          href: null,
        },
        {
          type: 'text',
          text: {
            content: 'Bạn có thể tăng tốc độ nói trong phần Setting → Speed',
            link: null,
          },
          annotations: {
            bold: false,
            italic: true,
            strikethrough: false,
            underline: false,
            code: true,
            color: 'default',
          },
          plain_text: 'Bạn có thể tăng tốc độ nói trong phần Setting → Speed',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: '53edd90f-804f-42b4-a238-ee9f09166cb7',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'video',
    video: {
      caption: [],
      type: 'external',
      external: { url: 'https://vimeo.com/548240693/ab2be19644' },
    },
  },
  {
    object: 'block',
    id: '804354ac-fdb0-42d7-939f-ad646ba99202',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'paragraph',
    paragraph: { text: [] },
  },
  {
    object: 'block',
    id: '05b97524-83b8-4f3b-ab10-07cea1e4d9d8',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'paragraph',
    paragraph: {
      text: [
        {
          type: 'mention',
          mention: {
            type: 'page',
            page: { id: 'f2b4a2bf-97c6-428f-8218-2a974adcaf7c' },
          },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'default',
          },
          plain_text: 'Untitled',
          href: 'https://www.notion.so/f2b4a2bf97c6428f82182a974adcaf7c',
        },
        {
          type: 'text',
          text: { content: ' ', link: null },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'default',
          },
          plain_text: ' ',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: 'd08330f8-f32d-4af0-aeaa-cebc629e7870',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'paragraph',
    paragraph: { text: [] },
  },
  {
    object: 'block',
    id: '03611382-6548-41a9-bc2c-d4a6806df45e',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'unsupported',
    unsupported: {},
  },
  {
    object: 'block',
    id: 'c2813462-d29a-4fd9-923a-7f07896e2e87',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'heading_2',
    heading_2: {
      text: [
        {
          type: 'text',
          text: { content: 'Tìm Hiểu Các Bước Thực Hiện', link: null },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'yellow_background',
          },
          plain_text: 'Tìm Hiểu Các Bước Thực Hiện',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: '66c978b3-c6ab-4952-a562-dc24b682b746',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'video',
    video: {
      caption: [],
      type: 'external',
      external: {
        url: 'https://player.vimeo.com/video/549085358?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
      },
    },
  },
  {
    object: 'block',
    id: '15cf9e59-e334-4d01-b4cb-66472aeb6ea0',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'heading_2',
    heading_2: {
      text: [
        {
          type: 'text',
          text: {
            content: 'Phần 1 - Nhân Khẩu Học & Các Công Cụ Để Lấy Dữ Liệu',
            link: null,
          },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'yellow_background',
          },
          plain_text: 'Phần 1 - Nhân Khẩu Học & Các Công Cụ Để Lấy Dữ Liệu',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: 'f781e1d3-f6c3-449a-a22c-7bf627dcfbaf',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'video',
    video: {
      caption: [],
      type: 'external',
      external: {
        url: 'https://player.vimeo.com/video/549084099?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
      },
    },
  },
  {
    object: 'block',
    id: '9b2045f9-bf01-464d-bf35-29a5068d392e',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'heading_2',
    heading_2: {
      text: [
        {
          type: 'text',
          text: { content: 'Phần 2 - Ưu Đãi', link: null },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'yellow_background',
          },
          plain_text: 'Phần 2 - Ưu Đãi',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: 'd70167d0-d640-4573-ac36-9bcd397df848',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'video',
    video: {
      caption: [],
      type: 'external',
      external: {
        url: 'https://player.vimeo.com/video/549084818?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
      },
    },
  },
  {
    object: 'block',
    id: '2f332358-d4b0-4200-b7e9-a3efe5d74efc',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'heading_2',
    heading_2: {
      text: [
        {
          type: 'text',
          text: { content: 'Phần 3 - Landing Page', link: null },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'yellow_background',
          },
          plain_text: 'Phần 3 - Landing Page',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: 'b07c0c07-1720-4bc3-9a60-1acd037aaefa',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'video',
    video: {
      caption: [],
      type: 'external',
      external: {
        url: 'https://player.vimeo.com/video/549084952?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
      },
    },
  },
  {
    object: 'block',
    id: '12821399-5215-42a2-8b64-72668cb19604',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'heading_2',
    heading_2: {
      text: [
        {
          type: 'text',
          text: { content: 'Phần 4 - Nguồn Khách Đến', link: null },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'yellow_background',
          },
          plain_text: 'Phần 4 - Nguồn Khách Đến',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: 'cfd08fe8-6d91-4d81-a900-805f430a13a6',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'video',
    video: {
      caption: [],
      type: 'external',
      external: {
        url: 'https://player.vimeo.com/video/549085175?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
      },
    },
  },
  {
    object: 'block',
    id: 'a71fb8ee-f1d6-4f3e-ba16-ac86f83f18a7',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'heading_2',
    heading_2: {
      text: [
        {
          type: 'text',
          text: { content: 'Phần 5 - Quảng Cáo', link: null },
          annotations: {
            bold: false,
            italic: false,
            strikethrough: false,
            underline: false,
            code: false,
            color: 'yellow_background',
          },
          plain_text: 'Phần 5 - Quảng Cáo',
          href: null,
        },
      ],
    },
  },
  {
    object: 'block',
    id: '8b871e9d-e690-4078-b57f-622352fa0fe0',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'video',
    video: {
      caption: [],
      type: 'external',
      external: {
        url: 'https://player.vimeo.com/video/549116157?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
      },
    },
  },
  {
    object: 'block',
    id: '65404f76-0096-4021-82f4-38ced4876853',
    created_time: '2021-10-14T07:36:00.000Z',
    last_edited_time: '2021-10-14T07:36:00.000Z',
    has_children: false,
    archived: false,
    type: 'paragraph',
    paragraph: { text: [] },
  },
]

**Comment by onlineworld69** [comment]
I found the bug. It's the type: "mention" in paragraph block (check the attachment). I think this is new that's why I broke?  @9gustin 
<img width="729" alt="Screen Shot 2021-10-15 at 09 58 42" src="https://user-images.githubusercontent.com/13715145/137425418-daaab674-0354-4158-b5d2-a7d79a112428.png">

My solution to fix it was to filter just type "text" in paragraph before deconstructing it.  Please advise if u have a better idea. Tks! 

`
const SpanText = ({ text, id }) => {
  if (!text) return null
// Here is the fix 
  const getTypeText = text.filter((i) => i.type === 'text')

  return getTypeText.map((value, i) => {
    const {
      annotations: { bold, code, color, italic, strikethrough, underline },
      text,
    } = value

    return (
      <span
        key={id + i}
        className={[
          bold ? 'font-bold' : '',
          code ? 'bg-gray-100 p-1 font-mono text-sm rounded-md' : '',
          italic ? 'italic' : '',
          strikethrough ? 'line-through' : '',
          underline ? 'underline' : '',
        ].join(' ')}
        style={color !== 'default' ? { color } : {}}
      >
     
        {text.link ? (
          <a href={text.link.url} className="underline">
            {text.content}
          </a>
        ) : (
          text.content
        )}
      </span>
    )
  })
}
`

**Comment by 9gustin** [comment]
Working on it now

**Comment by 9gustin** [comment]
Solved in [v3.3.1](https://www.npmjs.com/package/@9gustin/react-notion-render) for now not applied special styles, just use links for mentions, i consider improve this in the future
