### ISSUE TITLE
Make anotations more semantic 

### ISSUE THREAD

**Issue by dashkevych** [9gustin/react-notion-render#75]
It would be great if block annotations -- bold, code, italic, strikethrough, underline -- had more semantic output by using HTML tags instead of a `<span>` tag with a special CSS class.

1. bold  - `<strong>`
2. code - `<code>`
3. italic - `<em>`
4. strikethrough - `<s>`
5. underline - `<u>`

**Comment by 9gustin** [comment]
nice! I keep it in mind

**Comment by 9gustin** [comment]
This would be solved in next version. Thanks to @mrzmyr for #82 

The only thing to take in count it's, you can combine text formats, like bold and underline, or everyone, in this cases the package put one of this.

Example. If you make a text bold and underline the text will be contained by a `<strong>` tag

Notice here when this version was deployed. 😃

**Comment by 9gustin** [comment]
Beta version was released ✨🚀 -> https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.5.0-beta.1

**Comment by 9gustin** [comment]
Released, I close this 😄
