### ISSUE TITLE
Update contribution section in documentation

### ISSUE THREAD

**Issue by mrzmyr** [9gustin/react-notion-render#78]
Let's add the steps `yarn` (to install dependencies) and `yarn link` to the contribution section so one can use it to run the example and start contributing (i.e. https://github.com/9gustin/react-notion-render/blob/main/dev-example/pages/_app.js#L2).

I just ran into the problem when I tried to run the example.

**Comment by 9gustin** [comment]
Section improved, i would be deployed in next version -> https://github.com/9gustin/react-notion-render/tree/development#contributions 🚀

**Comment by mrzmyr** [comment]
Looks good to me ✨May I would put the directory structure in a table:

| Directory | Description
| ---------- | ----------- |
`dev-example` | App maded with next.js, this app have the output of `src` as a package. You can test what are you developing here.
`src` | the package `@9gustin/react-notion-render`
`src/components` | React components
`src/components/common` | here are the "simple components", like all notion components and generic components(Link for example).
`src/components/core` | here are the logic components, the core of the package
`src/components/core/Render` | Render are the package exported component, the entry point of the package. It receives a list of blocks and render it.
`src/components/core/Text` | The text in notion are complex, this component contemplate text variants, like bold, italic. Also contemplate links.
`src/hoc` | Higher order components / in there we apply some logic rules.
`src/hoc/withContentValidation` | This HOC it's a filter before to pass the `Notion block` to the common components. almost every components are wrapped by this, and this objetive it's simplify props that the component would receive, applying package rules.
`src/hoc/withCustomComponent` | The package supports [custom components](#custom-components). This HOC make it possible. before to render text validate if the text are a custom component and render it.
`src/styles` | package styles. We just use plain css, the objective it's not apply much style, just the necessary. We use :global() to avoid compile problems with the className
`src/types` | Types of the package
`src/utils` | Common functions
`src/index.tsx` | All that the package exports outside

**Comment by 9gustin** [comment]
Look's nice! applied 👍🏼

**Comment by 9gustin** [comment]
Released, I close this 😄
