### ISSUE TITLE
Add 'supported blocks' section to documentation

### ISSUE THREAD

**Issue by mrzmyr** [9gustin/react-notion-render#80]
Let's add a supported blocks section to the docs.

https://github.com/splitbee/react-notion#supported-blocks

**Comment by 9gustin** [comment]
Added! i would be deployed in next version -> https://github.com/9gustin/react-notion-render/tree/development#supported-blocks 🚀

**Comment by mrzmyr** [comment]
Looks great!

**Comment by 9gustin** [comment]
Released, I close this 😄
