### ISSUE TITLE
Add new prop "onlyTitles" to render titles without anchor

### ISSUE THREAD

**Issue by nublson** [9gustin/react-notion-render#92]
I've been using this library for 2 weeks now, I find it amazing and with a lot of potentials to become the community's favorite React notion block rendering library, however, titles are rendered as anchors and I found this a problem.

### What would you like to be added:
I think it would be better for the developer to have a property to make this choice.

Add a prop to `Render` component:

```jsx
<Render blocks={blocks} onlyTitles />
```

And now the titles `h1`, `h2` and `h3` will be rendered without being a anchor.

### Why is this needed:
Each block has a defined type, and I think it's better for them to be rendered with the same type and behavior as they were created in Notion, this allows more control over them.

**Comment by 9gustin** [comment]
Good point, I'll be working on it

**Comment by nublson** [comment]
Thank you very much!

**Comment by nublson** [comment]
@9gustin I actually already added these feature, however, I can not test because the next app inside dev-example does not work!

I don't know why! It says that some hook is being called outside of a functional component.

**Comment by 9gustin** [comment]
Oh, recently i improved the doc about collaborations in the README.md file, and talked about running the dev-example. Did you make an npm install inside of ./dev-example folder?

**Comment by nublson** [comment]
Yes, I did id! But I'll try again!

**Comment by 9gustin** [comment]
Can you give me a screenshot of this error? to fix it to prevent it from happening to more devs 😄

**Comment by 9gustin** [comment]
hmmm okey, this occurs because one react rule avoid to use hooks inside of functions. Did you have this code pushed into your fork? to check it. Or it pass when you run the main branch(without changes)?

**Comment by nublson** [comment]
@9gustin  I have this code in my fork!

**Comment by 9gustin** [comment]
@nublson Hey! so much time, sorry. Did you installed the dependencies with yarn? trying i have noticed that this error happens installing the dependencies with yarn. I will try to fix it but for the moment you can use npm.

**Comment by 9gustin** [comment]
Beta version with this released at https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.6.0-beta.0 🚀

**Comment by nublson** [comment]
> @nublson Hey! so much time, sorry. Did you installed the dependencies with yarn? trying i have noticed that this error happens installing the dependencies with yarn. I will try to fix it but for the moment you can use npm.

Yes @9gustin I installed with Yarn! Okay, I'll try to use NPM!

**Comment by nublson** [comment]
> Beta version with this released at https://www.npmjs.com/package/@9gustin/react-notion-render/v/3.6.0-beta.0 rocket

Amazing my man, I'll try right now!

**Comment by 9gustin** [comment]
I'll close this issue because i already release the version ([release](https://github.com/9gustin/react-notion-render/releases/tag/v3.6)). I have opened a new issue to review the problem with yarn: #102 

Thanks 💖

**Comment by nublson** [comment]
Amazin @9gustin ! Thank you very much!
